services:
    link_button.form.extension:
        class: SymfonyContrib\Bundle\LinkButtonBundle\Form\Extension\LinkButtonExtension
        tags:
            - name: form.type_extension
              extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType
